{
 "title": "Sandbox Cisco",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Rate of bytes entering the interfaces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(intf_stats_in_octets[1m])", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Interfaces Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "intf_stats_operational_status{name=~\"GigabitEthernet1|GigabitEthernet2|GigabitEthernet3|Loopback2022\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_pool_percent_used{name=\"Processor\"}"
    }
   ]
  },
  {
   "title": "Bytes consumed by all processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(cpu_process_consumed_bytes{})"
    }
   ]
  }
 ]
}